context:
  version: 1.15.0

package:
  name: yaml-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-${{ version }}.tgz
  sha256: b93db2a985437355eb124d44ae60c0569f22cf19473eb0b6f41b8b0d7af579bd

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - yaml-language-server 2>&1 | grep -q 'Connection input stream is not set.'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Yaml Files
  homepage: https://github.com/redhat-developer/yaml-language-server
  repository: https://github.com/redhat-developer/yaml-language-server

extra:
  recipe-maintainers:
    - danielnachun
